# ============ init Section, Node ================
s1 = Section.create(name: 'NKN', sort: 9)
Node.create(name: '公告', sort: 99, summary: '...', section_id: s1.id)
Node.create(name: '新闻', sort: 98, summary: '...', section_id: s1.id)
Node.create(name: '问答', sort: 97, summary: '...', section_id: s1.id)
s2 = Section.create(name: '开发', sort: 8)
Node.create(name: '开发交流', sort: 89, summary: '...', section_id: s2.id)
Node.create(name: '开发教程', sort: 88, summary: '...', section_id: s2.id)
Node.create(name: '开发工具', sort: 87, summary: '...', section_id: s2.id)
s3 = Section.create(name: '挖矿', sort: 7)
Node.create(name: '挖矿交流', sort: 79, summary: '...', section_id: s3.id)
Node.create(name: '挖矿教程', sort: 78, summary: '...', section_id: s3.id)
Node.create(name: '挖矿工具', sort: 77, summary: '...', section_id: s3.id)
